version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: tainacan
      WORDPRESS_DB_PASSWORD: tainacan
      WORDPRESS_DB_NAME: tainacan
    volumes:
      - wordpress_data:/var/www/html
      - ./.deploy/wp-content/themes/tainacan-interface:/var/www/html/wp-content/themes/tainacan-interface
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tainacan
      MYSQL_USER: tainacan
      MYSQL_PASSWORD: tainacan
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  wordpress_data:
  db_data:
